import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UsersProvider } from "@/contextApi/UsersContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auxillary System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UsersProvider>
          <Navbar />
          {children}
        </UsersProvider>
      </body>
    </html>
  );
}
